version: '3.8'

services:
  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Main RabbitMQ port
      - "15672:15672" # Management console
    networks:
      - rabbitmq-network

  # MySQL service
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - rabbitmq-network

  # Producer microservice
  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - rabbitmq
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/producer_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8075:8075"
    networks:
      - rabbitmq-network

  # Consumer1 microservice
  consumer1:
    build:
      context: ./consumer1
      dockerfile: Dockerfile
    container_name: consumer1
    depends_on:
      - rabbitmq
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/consumer1_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8091
    ports:
      - "8091:8091"
    networks:
      - rabbitmq-network

  # Consumer2 microservice
  consumer2:
    build:
      context: ./consumer2
      dockerfile: Dockerfile
    container_name: consumer2
    depends_on:
      - rabbitmq
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/consumer2_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8092
    ports:
      - "8092:8092"
    networks:
      - rabbitmq-network

  # Consumer3 microservice
  consumer3:
    build:
      context: ./consumer3
      dockerfile: Dockerfile
    container_name: consumer3
    depends_on:
      - rabbitmq
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/consumer3_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8093
    ports:
      - "8093:8093"
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
